providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["npm ci --include=dev --ignore-scripts"]

[phases.build]
cmds = ["npm run build:showcase"]

[start]
cmd = "npm run start:showcase"
